export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const GUEST_USER_SUCCESS = 'GUEST_USER_SUCCESS';
export const GUEST_USER_FAILED = 'GUEST_USER_FAILED';
export const GUEST_USER_DATA = 'GUEST_USER_DATA';

export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
